events {
    worker_connections   2000;

    # use [ kqueue | epoll | /dev/poll | select | poll ];
    use epoll;
}

http {

    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;
        

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}